Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,14 +20,30 @@ jobs:
           distribution: 'temurin'
           cache: maven   
       - name: Build with Maven
-        run: mvn clean package
+        run: |
+          mvn clean package
+          if [ $? -ne 0 ]; then
+            echo "Build failed. Exiting..."
+            exit 1
+          fi
       - name: Run tests with Maven
-        run: mvn test
+        run: |
+          mvn test
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Exiting..."
+            exit 1
+          fi
+      - name: Generate Version
+        id: version
+        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
+      - name: Display Version
+        run: echo "Version is ${{ env.VERSION }}"
       - name: Upload artifact
         uses: actions/upload-artifact@v3.1.3
         with:
           name: to-do-artifact
-          path: .  
+          path: .
+          if-no-files-found: error 
 
   deploy-dev:
     runs-on: ubuntu-latest
